
    let products = [
        {
          id: 1,
          img: "https://media6.ppl-media.com/tr:h-250,w-250,c-at_max,oi-@@mediafiles@mailers@banners@1659451450_new-tag.png,ow-115,ofo-top_right,dpr-2/static/img/product/328788/good-vibes-matte-liquid-lipstick-5-2ml-nude-brown_1_display_1677566867_00349fba.jpg",
          name: "MYGLAMM FACE & LIP COMBO",
          prevprice: "₹1039",
          price: "₹939",
          description: " Enjoy Free Gift",
          detail:"Get the festive glow on with MyGlamm Hydra-Glow – Face & Lip Combo. Begin by washing off the dirt, pollution and makeup with Glow Iridescent Brightening Foam Cleanser. Follow up with Glow Iridescent Brightening Sheet Mask for instant radiance and hydration. Lastly, choose your favourite shade of MyGlamm LIT pH Lip Balm and give your lips some A-level hydration",
          qty:1
        },
    
        {
          id: 2,
          img: "https://media6.ppl-media.com/tr:h-250,w-250,c-at_max,oi-AD_35x235_small_kJWM53nMn1.png,ow-60,ofo-top_right,dpr-2/static/img/product/271225/bajaj-almond-drops-hair-oil-500-ml-20_9_display_1659089918_9c6c8205.jpg",
          name: " Bajaj almond HairOil",
          prevprice: "₹539",
          price: "₹239",
          description: " flat 20% off",
          detail:"Get the festive glow on with MyGlamm Hydra-Glow – Face & Lip Combo. Begin by washing off the dirt, pollution and makeup with Glow Iridescent Brightening Foam Cleanser. Follow up with Glow Iridescent Brightening Sheet Mask for instant radiance and hydration. Lastly, choose your favourite shade of MyGlamm LIT pH Lip Balm and give your lips some A-level hydration",
          qty:1

        },
        {
          id: 3,
          img: "https://media6.ppl-media.com/tr:h-250,w-250,c-at_max,oi-AD_35x235_small_kJWM53nMn1.png,ow-60,ofo-top_right,dpr-2/static/img/product/197370/lakme-sun-expert-ultra-matte-spf-40-pa-compact-7-g_3_display_1556887770_f561c73c.jpg",
          name: " Lakme Sunscreen",
          prevprice: "₹899",
          price: "₹699",
          description: " enjoy free gift",
          detail:"Get the festive glow on with MyGlamm Hydra-Glow – Face & Lip Combo. Begin by washing off the dirt, pollution and makeup with Glow Iridescent Brightening Foam Cleanser. Follow up with Glow Iridescent Brightening Sheet Mask for instant radiance and hydration. Lastly, choose your favourite shade of MyGlamm LIT pH Lip Balm and give your lips some A-level hydration",
          qty:1

        },
        {
          id: 4,
          img: " https://media6.ppl-media.com/tr:h-250,w-250,c-at_max,oi-AD_35x235_small_kJWM53nMn1.png,ow-60,ofo-top_right,dpr-2/static/img/product/287358/dermdoc-1-1-percentage-hyaluronic-moisturizing-under-eye-serum-15-ml-under-eye-serum-lightweight-serum-paraben-free-sulfate-free-cruelty-free-under-eye-serum_16_display_1667464339_1ce6176c.jpg",
          name: " Dermdoc Under Eye  Serum",
          prevprice: "₹399",
          price: "₹299",
          description: " enjoy free gift",
          detail:"Get the festive glow on with MyGlamm Hydra-Glow – Face & Lip Combo. Begin by washing off the dirt, pollution and makeup with Glow Iridescent Brightening Foam Cleanser. Follow up with Glow Iridescent Brightening Sheet Mask for instant radiance and hydration. Lastly, choose your favourite shade of MyGlamm LIT pH Lip Balm and give your lips some A-level hydration",
        },
        {
          id: 5,
          img: "https://media6.ppl-media.com/tr:h-250,w-250,c-at_max,oi-AD_35x235_small_kJWM53nMn1.png,ow-60,ofo-top_right,dpr-2/static/img/product/348148/matrix-opti-care-professional-ultra-smoothing-shampoo-opti-care-professional-anti-frizz-conditioner-200ml-98g-for-straight-hair_1_display_1678388470_c77a2e22.jpg",
          name: " Smooth Care Opti.Care",
          prevprice: "₹539",
          price: "₹400",
          description: " flat 10% off",
          detail:"Get the festive glow on with MyGlamm Hydra-Glow – Face & Lip Combo. Begin by washing off the dirt, pollution and makeup with Glow Iridescent Brightening Foam Cleanser. Follow up with Glow Iridescent Brightening Sheet Mask for instant radiance and hydration. Lastly, choose your favourite shade of MyGlamm LIT pH Lip Balm and give your lips some A-level hydration",
        },
        {
          id: 6,
          img: "https://media6.ppl-media.com/tr:h-250,w-250,c-at_max,oi-AD_35x235_small_kJWM53nMn1.png,ow-60,ofo-top_right,dpr-2/static/img/product/337332/ny-bae-runway-radiance-compact-powder-pale-ivory-9gm-39-95_5_display_1670233060_064eaf69.jpg",
          name: " Compact Skin Powder",
          prevprice: "₹599",
          price: "₹439",
          description: " enjoy free gift",
          detail:"Get the festive glow on with MyGlamm Hydra-Glow – Face & Lip Combo. Begin by washing off the dirt, pollution and makeup with Glow Iridescent Brightening Foam Cleanser. Follow up with Glow Iridescent Brightening Sheet Mask for instant radiance and hydration. Lastly, choose your favourite shade of MyGlamm LIT pH Lip Balm and give your lips some A-level hydration",
        },
        {
          id: 7,
          img: "https://media6.ppl-media.com/tr:h-235,w-235,c-at_max,oi-purplle_exclusive_base_1__1__BytKq6D4b.png,ofo-top_right,dpr-2/static/img/product/267470/ny-bae-pro-dual-brush-foundation-and-blush_5_display_1670492363_34a7a149.jpg",
          name: " Foundation And  Blush",
          prevprice: "₹999",
          price: "₹939",
          description: " enjoy free gift",
          detail:"Get the festive glow on with MyGlamm Hydra-Glow – Face & Lip Combo. Begin by washing off the dirt, pollution and makeup with Glow Iridescent Brightening Foam Cleanser. Follow up with Glow Iridescent Brightening Sheet Mask for instant radiance and hydration. Lastly, choose your favourite shade of MyGlamm LIT pH Lip Balm and give your lips some A-level hydration",
        },
        {
          id: 8,
          img: "https://media6.ppl-media.com/tr:h-250,w-250,c-at_max,oi-AD_35x235_small_kJWM53nMn1.png,ow-60,ofo-top_right,dpr-2/static/img/product/133204/matrix-biolage-deep-smoothing-shampoo-200ml-16_2_display_1676783408_bcb11a24.jpg",
          name: " Biolace Professional Shampoo",
          prevprice: "₹199",
          price: "₹139",
          description: " enjoy free gift",
          detail:"Get the festive glow on with MyGlamm Hydra-Glow – Face & Lip Combo. Begin by washing off the dirt, pollution and makeup with Glow Iridescent Brightening Foam Cleanser. Follow up with Glow Iridescent Brightening Sheet Mask for instant radiance and hydration. Lastly, choose your favourite shade of MyGlamm LIT pH Lip Balm and give your lips some A-level hydration",
        },
        {
          id: 9,
          img: "https://media6.ppl-media.com/tr:h-250,w-250,c-at_max,oi-AD_35x235_small_kJWM53nMn1.png,ow-60,ofo-top_right,dpr-2/static/img/product/125049/lakme-9-to-5-primer-matte-powder-foundation-compact-ivory-cream-9-g_7_display_1666091988_b0eb3c52.jpg",
          name: " Lakme Smoother creme",
          prevprice: "₹399",
          price: "₹200",
          description: " flat 5% off",
          detail:"Get the festive glow on with MyGlamm Hydra-Glow – Face & Lip Combo. Begin by washing off the dirt, pollution and makeup with Glow Iridescent Brightening Foam Cleanser. Follow up with Glow Iridescent Brightening Sheet Mask for instant radiance and hydration. Lastly, choose your favourite shade of MyGlamm LIT pH Lip Balm and give your lips some A-level hydration",
        },
        {
          id: 10,
          img: " https://media6.ppl-media.com/tr:h-250,w-250,c-at_max,oi-AD_35x235_small_kJWM53nMn1.png,ow-60,ofo-top_right,dpr-2/static/img/product/283373/loreal-paris-total-repair-5-repairing-conditioner-180-ml-18_2_display_1655200839_047c7114.jpg",
          name: " LOREAL Restoring Conditioner",
          prevprice: "₹999",
          price: "₹839",
          description: " flat 15% off",
          detail:"Get the festive glow on with MyGlamm Hydra-Glow – Face & Lip Combo. Begin by washing off the dirt, pollution and makeup with Glow Iridescent Brightening Foam Cleanser. Follow up with Glow Iridescent Brightening Sheet Mask for instant radiance and hydration. Lastly, choose your favourite shade of MyGlamm LIT pH Lip Balm and give your lips some A-level hydration",
        },
        {
          id: 11,
          img: " https://media6.ppl-media.com/tr:h-250,w-250,c-at_max,oi-AD_35x235_small_kJWM53nMn1.png,ow-60,ofo-top_right,dpr-2/static/img/product/267668/love-beauty-and-planet-argan-oil-and-lavender-sulfate-free-smooth-and-serene-shampoo-200ml_2_display_1638779147_e845441e.jpg",
          name: " Love & Beauty Shampoo",
          prevprice: "₹599",
          price: "₹439",
          description: " enjoy free gift",
          detail:"Get the festive glow on with MyGlamm Hydra-Glow – Face & Lip Combo. Begin by washing off the dirt, pollution and makeup with Glow Iridescent Brightening Foam Cleanser. Follow up with Glow Iridescent Brightening Sheet Mask for instant radiance and hydration. Lastly, choose your favourite shade of MyGlamm LIT pH Lip Balm and give your lips some A-level hydration",
        },
        {
          id: 12,
          img: "https://media6.ppl-media.com/tr:h-250,w-250,c-at_max,dpr-2/static/img/product/185620/wow-skin-science-onion-black-seed-oil-shampoo-300-ml_1_display_1671019389_4b2af752.jpg",
          name: " Wow Shampoo",
          prevprice: "₹899",
          price: "₹739",
          description: " enjoy free gift",
          detail:"Get the festive glow on with MyGlamm Hydra-Glow – Face & Lip Combo. Begin by washing off the dirt, pollution and makeup with Glow Iridescent Brightening Foam Cleanser. Follow up with Glow Iridescent Brightening Sheet Mask for instant radiance and hydration. Lastly, choose your favourite shade of MyGlamm LIT pH Lip Balm and give your lips some A-level hydration",
        },
        {
          id: 13,
          img: "https://media6.ppl-media.com/tr:h-235,w-235,c-at_max,dpr-2/static/img/product/300927/aqualogica-radiance-mousse-night-gel-with-watermelon-and-niacinamide_2_display_1674191405_20a5efbe.jpg",
          name: " Aqualogica Radiance creme",
          prevprice: "₹499",
          price: "₹399",
          description: " enjoy free gift",
          detail:"Get the festive glow on with MyGlamm Hydra-Glow – Face & Lip Combo. Begin by washing off the dirt, pollution and makeup with Glow Iridescent Brightening Foam Cleanser. Follow up with Glow Iridescent Brightening Sheet Mask for instant radiance and hydration. Lastly, choose your favourite shade of MyGlamm LIT pH Lip Balm and give your lips some A-level hydration",
        },
        {
          id: 14,
          img: "https://media6.ppl-media.com/tr:h-235,w-235,c-at_max,dpr-2/static/img/product/103530/nike-pink-edt-for-women-100-ml_1_display_1466168619_96e0f83f.jpg",
          name: " Nike Women",
          prevprice: "₹679",
          price: "₹569",
          description: " enjoy free gift",
        },
        {
          id: 15,
          img: " https://media6.ppl-media.com/tr:h-250,w-250,c-at_max,oi-purplle_exclusive_base_1__1__BytKq6D4b.png,ofo-top_right,dpr-2/static/img/product/272885/ny-bae-kohl-black-the-big-apple-of-my-eye-14_5_display_1680243981_88bf8dc2.jpg",
          name: " Intense Black Kajal",
          prevprice: "₹99",
          price: "₹89",
          description: " enjoy free gift",
        },
        {
          id: 16,
          img: "https://media6.ppl-media.com/tr:h-250,w-250,c-at_max,dpr-2/static/img/product/200194/swiss-beauty-ultra-smooth-matte-lip-liquid-lipstick-color-stay-real-nude-6-ml_2_display_1679481262_b869792f.jpg",
          name: " Matte Lip Liquid Lipstic",
          prevprice: "₹399",
          price: "₹239",
          description: " flat 10% off",
        },
        {
          id: 17,
          img: "https://media6.ppl-media.com/tr:h-235,w-235,c-at_max,oi-purplle_exclusive_base_1__1__BytKq6D4b.png,ofo-top_right,dpr-2/static/img/product/254352/cuff-n-lashes-colorpots-yaas_1_display_1635162699_e31971ab.jpg",
          name: "Clean & Clear",
          prevprice: "₹499",
          price: "₹420",
          description: " flat 10% off",
        },
        {
          id: 18,
          img: "https://media6.ppl-media.com/tr:h-250,w-250,c-at_max,dpr-2/static/img/product/284357/ny-bae-truly-matte-liquid-eyeliner-pretty-pink-06-4-5-ml_6_display_1675682258_20ae2286.jpg",
          name: " Matte Liner",
          prevprice: "₹779",
          price: "₹639",
          description: " flat 10% off",
        },
        {
          id: 19,
          img: "https://media6.ppl-media.com/tr:h-250,w-250,c-at_max,dpr-2/static/img/product/342337/lovechild-masaba-wings-for-your-eyes-mood-proof-eyeliner-coal-black_8_display_1681988388_e5acccbc.jpg",
          name: " Eye Liner",
          prevprice: "₹899",
          price: "₹2939",
          description: " enjoy free gift",
        },
        {
          id: 20,
          img: "https://media6.ppl-media.com/tr:h-235,w-235,c-at_max,oi-purplle_exclusive_base_1__1__BytKq6D4b.png,ofo-top_right,dpr-2/static/img/product/257671/ny-bae-creme-nail-paint-pale-ivory-32-10-ml_5_display_1674547668_07525787.jpg",
          name: " Nykaa Creme Nail Paint",
          prevprice: "₹899",
          price: "₹2939",
          description: " enjoy free gift",
        },
        {
          id: 21,
          img: "https://media6.ppl-media.com/tr:h-235,w-235,c-at_max,oi-Best_seller_700x700base_gUMVzNGWt_.png,ofo-top_right,dpr-2/static/img/product/263514/ny-bae-eye-love-volumizing-mascara-8ml_6_display_1681878721_fae122c7.jpg",
          name: "Eye Mascara",
          prevprice: "₹1039",
          price: "₹939",
          description: "enjoy free gift",
        },
    
        {
          id: 22,
          img: "https://media6.ppl-media.com/tr:h-235,w-235,c-at_max,dpr-2/static/img/product/307394/sugar-pop-longwear-kajal-03-brown-intense-brown-kohl-kajal-for-women-l-long-lasting-smudge-proof-water-proof-single-stroke-velvet-finish-l-lasts-up-to-16-hours_1_display_1656059997_d69bce54.jpg",
          name: " Sugar Pop Longwear Kajal",
          prevprice: "₹539",
          price: "₹239",
          description: " enjoy free gift",
        },
        {
          id: 23,
          img: "https://media6.ppl-media.com/tr:h-235,w-235,c-at_max,oi-purplle_exclusive_base_1__1__BytKq6D4b.png,ofo-top_right,dpr-2/static/img/product/263513/ny-bae-eye-love-curling-mascara-8ml_1_display_1682060955_7bb4e20f.jpg",
          name: " EYE Love Volumizing Mascara",
          prevprice: "₹899",
          price: "₹699",
          description: " enjoy free gift",
        },
        {
          id: 24,
          img: "https://media6.ppl-media.com/tr:h-235,w-235,c-at_max,oi-@@mediafiles@mailers@banners@1659451450_new-tag.png,ow-115,ofo-top_right,dpr-2/static/img/product/266408/faces-canada-comfy-matte-lip-color-comfortable-10-hours-longstay-matte-finish-almond-oil-and-vitamin-e-infused-getting-ready-02-3ml_1_display_1669028274_c1635983.jpg",
          name: " EYE Love Volumizing Mascara",
          prevprice: "₹599",
          price: "₹490",
          description: " enjoy free gift",
        },
        {
          id: 25,
          img: "https://media6.ppl-media.com/tr:h-235,w-235,c-at_max,dpr-2/static/img/product/292335/sugar-pop-longwear-compact-01-sand30gm_1_display_1664190114_e290b758.jpg",
          name: " Blossom Weekend",
          prevprice: "₹399",
          price: "₹288",
          description: " enjoy free gift",
        },
        {
          id: 26,
          img: "https://media6.ppl-media.com/tr:h-235,w-235,c-at_max,dpr-2/static/img/product/276985/ny-bae-rose-loose-powder-5-8-ml_5_display_1669268270_1804dbde.jpg",
          name: " Rose Lose  Powder",
          prevprice: "₹899",
          price: "₹739",
          description: " enjoy free gift",
        },
        {
          id: 27,
          img: "https://media6.ppl-media.com/tr:h-235,w-235,c-at_max,oi-purplle_exclusive_base_1__1__BytKq6D4b.png,ofo-top_right,dpr-2/static/img/product/269994/purplle-dream-blend-beauty-blender_1_display_1657201479_505871e4.jpg",
          name: " Dream Blender",
          prevprice: "₹589",
          price: "₹439",
          description: " enjoy free gift",
        },
        {
          id: 28,
          img: "https://media6.ppl-media.com/tr:h-235,w-235,c-at_max,oi-purplle_exclusive_base_1__1__BytKq6D4b.png,ofo-top_right,dpr-2/static/img/product/269481/cuffs-n-lashes-eyelashes-glue_2_display_1680514388_5065fff8.jpg",
          name: " Eye Lash Qlue",
          prevprice: "₹899",
          price: "₹670",
          description: " enjoy free gift",
        },
        {
          id: 29,
          img: "https://media6.ppl-media.com/tr:h-235,w-235,c-at_max,dpr-2/static/img/product/292326/sugar-pop-matte-lipstick-01-taupe_1_display_1650947543_7fc0403e.jpg",
          name: " Matte Lipstick",
          prevprice: "₹1199",
          price: "₹999",
          description: " enjoy free gift",
        },
        {
          id: 30,
          img: "https://media6.ppl-media.com/tr:h-235,w-235,c-at_max,oi-@@mediafiles@mailers@banners@1659451450_new-tag.png,ow-115,ofo-top_right,dpr-2/static/img/product/270340/purplle-blushing-in-berry-matte-blush-palette-10-5-gm_8_display_1662362057_74213ad9.jpg",
          name: " Blushing in Berry",
          prevprice: "₹999",
          price: "₹939",
          description: " enjoy free gift",
        },
        {
          id: 31,
          img: "https://media6.ppl-media.com/tr:h-235,w-235,c-at_max,oi-purplle_exclusive_base_1__1__BytKq6D4b.png,ofo-top_right,dpr-2/static/img/product/284114/ny-bae-makeup-pouch-light-pink_4_display_1673505530_e760c690.jpg",
          name: " Makeup Pouch",
          prevprice: "₹899",
          price: "₹739",
          description: " enjoy free gift",
        },
        {
          id: 32,
          img: "https://media6.ppl-media.com/tr:h-235,w-235,c-at_max,oi-purplle_exclusive_base_1__1__BytKq6D4b.png,ofo-top_right,dpr-2/static/img/product/269477/cuffsnlashes-makeup-brushes-set-of-14_2_display_1654692513_000289c6.jpg",
          name: " Makeup Brushe's",
          prevprice: "₹399",
          price: "₹299",
          description: " Enjoy Free Gift",
        },
        {
          id: 33,
          img: "https://media6.ppl-media.com/tr:h-235,w-235,c-at_max,oi-purplle_exclusive_base_1__1__BytKq6D4b.png,ofo-top_right,dpr-2/static/img/product/269477/cuffsnlashes-makeup-brushes-set-of-14_2_display_1654692513_000289c6.jpg",
          name: " Makeup Brushe's",
          prevprice: "₹399",
          price: "₹299",
          description: " Enjoy Free Gift",
        },
      ];


export default products;
